# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-03 14:34
from __future__ import unicode_literals

from django.db import migrations, models
import xyinc.api.models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='x',
            field=models.PositiveSmallIntegerField(validators=[xyinc.api.models.positive_validation]),
        ),
        migrations.AlterField(
            model_name='poi',
            name='y',
            field=models.PositiveSmallIntegerField(validators=[xyinc.api.models.positive_validation]),
        ),
    ]
